"""Generate DATA_MAP.md — a human-readable 'where does the data live' report,
built from the registry + the actual parse result so it never drifts."""
from __future__ import annotations

from collections import Counter, defaultdict

from .registry import FILE_RULES


def render(pages: list[dict], version: str) -> str:
    by_role_kinds: dict[str, Counter] = defaultdict(Counter)
    files_by_role: dict[str, list[str]] = defaultdict(list)
    for p in pages:
        files_by_role[p["role"]].append(p["source_path"])
        for e in p["records"]:
            by_role_kinds[p["role"]][e["kind"]] += 1

    lines = [
        "# Data Map — where the data lives",
        "",
        "> Generated by the importer from `importer/shardsea/registry.py` + the parse of "
        f"`{version}`. Do not edit by hand; re-run the importer to refresh.",
        "",
        "Each source file (matched by the first glob below, top to bottom) is handled by a "
        "*role*. Every file becomes a **page** (faithful prose, verbatim `raw_md`); catalog "
        "roles also extract typed **records**.",
        "",
        "## File → role",
        "",
        "| Glob (first match wins) | Role | What it produces |",
        "|---|---|---|",
    ]
    for glob, role, desc in FILE_RULES:
        lines.append(f"| `{glob}` | `{role}` | {desc} |")

    lines += ["", "## Records extracted from " + version, "",
              "| Role | Files | Record kinds (count) |", "|---|---|---|"]
    for role in sorted(files_by_role):
        kinds = by_role_kinds.get(role, Counter())
        kind_str = ", ".join(f"{k} ({n})" for k, n in sorted(kinds.items())) or "— (page only)"
        lines.append(f"| `{role}` | {len(files_by_role[role])} | {kind_str} |")

    total_kinds = Counter()
    for c in by_role_kinds.values():
        total_kinds.update(c)
    lines += ["", "## Totals by kind", ""]
    for k, n in sorted(total_kinds.items()):
        lines.append(f"- **{k}**: {n}")
    lines += ["", f"- **pages**: {len(pages)}", ""]

    lines += [
        "## Where each kind is stored",
        "",
        "Flexible core: **`entity`** (kind, slug, name, `tier`, `summary`, `effects`, "
        "`attrs_json` = every parsed field, `raw_md` = verbatim). Promoted typed tables:",
        "",
        "| Kind | Typed table |",
        "|---|---|",
        "| feat | `feat` |",
        "| discipline | `discipline` |",
        "| weapon | `weapon` |",
        "| armor / shield | `armor` |",
        "| archetype | `archetype` |",
        "| condition | `condition` |",
        "| action | `game_action` |",
        "| rune / material | *(entity + attrs_json only)* |",
        "",
        "Prose pages live in **`page`** (`body_md` rendered, `raw_md` verbatim). "
        "Version history for the changelog lives in **`snapshot`** + **`change_entry`**.",
        "",
    ]
    return "\n".join(lines)
